#!/usr/bin/env bash
# configure domain zone for subzone

if [ $# -eq 1 ]; then
    for i in www lb-01 web-01 web-02; do
    dnszone="$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    dnszone2="$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $i is a $dnszone record and points to $dnszone2"
    done
elif [ $# -eq 2 ]; then
    dnszone="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    dnszone2="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $2 is a $dnszone record and points to $dnszone2"
fi
