#!/usr/bin/env bash
# script to install nginx to server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
