#!/usr/bin/env bash
# script to install nginx to server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee index.nginx-debian.html > /var/www/html
sudo service nginx start
