#!/usr/bin/env bash
# 301 moved Permanently

new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
