#!/usr/bin/env bash
#script to configure custom http

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $new_string" /etc/nginx/sites-available/default
error="\\\terror_page 404 ^/xyz.html;\nlocation = ^/xyz {\nroot /var/www/html; \ninternal;\n}"
sudo sed -i "43i $error" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/xyz.html
directfile="/etc/nginx/sites-available/default"
sudo sed -i "42i \\\tadd_header X-Served-By $HOSTNAME;\n" $directfile
sudo service nginx start
