#!/usr/bin/env bash
#conf load balancer
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy
inserting="frontend http_front
\tbind *:80
\tmode http
\tdefault_backend http_behind
backend http_behind
\tmode http
\tbalance roundrobin
\toption forwardfor
\tserver 1047-web-01 34.74.97.250:80 check
\tserver 1047-web-02 34.234.79.159:80 check"
sudo sed -i "$inserting" /etc/haproxy/haproxy.cfg
sudo service haproxy start
