#!/usr/bin/env bash
# displaying "Holberton School"  "bad luck" 4 slot "good luck" 8 slot

n=1
while (( $n <= 10 ))
do
    n=$(( n+1 ))
    if [ "$n" -eq 5 ]
    then
        echo "bad luck"
    elif [ "$n" -eq 9 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
done
