#!/usr/bin/env bash
# displaying "Holberton School"  "bad luck" 4 slot "good luck" 8 slot

n=0
while (( n < 10 ))
do
    n=$(( n+1 ))
    if [ "$n" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$n" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
done
